// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar for the "Interview Prep" docs instance (docs-interview/).
 * Auto-generated from the folder structure — each subject gets its own
 * category via a _category_.json file.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  interviewSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
